version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1

commands:
  publish:
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Git LFS
          command: |
            git lfs pull
      - run: ./publish.sh

jobs:
  ap_northeast_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: ap-northeast-1
    steps:
      - publish

  af_south_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: af-south-1
    steps:
      - publish

  ap_east_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: ap-east-1
    steps:
      - publish

  ap_northeast_2:
    executor: aws-cli/default
    environment:
      TARGET_REGION: ap-northeast-2
    steps:
      - publish

  ap_south_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: ap-south-1
    steps:
      - publish

  ap_southeast_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: ap-southeast-1
    steps:
      - publish

  ap_southeast_2:
    executor: aws-cli/default
    environment:
      TARGET_REGION: ap-southeast-2
    steps:
      - publish

  ca_central_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: ca-central-1
    steps:
      - publish

  eu_north_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: eu-north-1
    steps:
      - publish

  eu_south_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: eu-south-1
    steps:
      - publish

  eu_central_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: eu-central-1
    steps:
      - publish

  eu_west_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: eu-west-1
    steps:
      - publish

  eu_west_2:
    executor: aws-cli/default
    environment:
      TARGET_REGION: eu-west-2
    steps:
      - publish

  eu_west_3:
    executor: aws-cli/default
    environment:
      TARGET_REGION: eu-west-3
    steps:
      - publish

  me_south_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: me-south-1
    steps:
      - publish

  sa_east_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: sa-east-1
    steps:
      - publish

  us_east_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: us-east-1
    steps:
      - publish

  us_east_2:
    executor: aws-cli/default
    environment:
      TARGET_REGION: us-east-2
    steps:
      - publish

  us_west_1:
    executor: aws-cli/default
    environment:
      TARGET_REGION: us-west-1
    steps:
      - publish

  us_west_2:
    executor: aws-cli/default
    environment:
      TARGET_REGION: us-west-2
    steps:
      - publish

workflows:
  version: 2
  publish:
    jobs:
      - ap_northeast_1:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master

#      - af_south_1:
#          context: public-lambda-layers
#          filters:
#            branches:
#              only:
#                - master

#      - ap_east_1:
#          context: public-lambda-layers
#          filters:
#            branches:
#              only:
#                - master

      - ap_northeast_2:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master

      - ap_south_1:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master

      - ap_southeast_1:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master

      - ap_southeast_2:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master

      - ca_central_1:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master

      - eu_north_1:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master

#      - eu_south_1:
#          context: public-lambda-layers
#          filters:
#            branches:
#              only:
#                - master

      - eu_central_1:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master

      - eu_west_1:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master

      - eu_west_2:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master

      - eu_west_3:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master

#      - me_south_1:
#          context: public-lambda-layers
#          filters:
#            branches:
#              only:
#                - master

      - sa_east_1:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master

      - us_east_1:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master

      - us_east_2:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master

      - us_west_1:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master

      - us_west_2:
          context: public-lambda-layers
          filters:
            branches:
              only:
                - master
